### PR TITLE
segregated gulag kills/deaths

### PR DESCRIPTION
**Pull request by osama-h-rana**
Subtracted the gulag kills and deaths from the match kills and deaths. Also added a new k/d for gulag

### CODE REVIEW

**Comment by saadmujeeb05** [comment]
Just add separate rows for Gulag Kills, Gulag Deaths and Gulag K/D. Don't subtract from the Kills, Deaths and K/D.

**Comment by osama-h-rana** [comment]
@saadmujeeb05 as mentioned in the linked issue, the goal is to exclude the gulag kills and deaths from the actual match stats. This is primarily because the two require vastly different skillsets to improve, and to equate them wouldn't be fair. That's why we're segregating them in the first place. 

I can add another stat for overall K/D

**Comment by saadmujeeb05** [comment]
The actual match stats contains the gulag stats as well so to get a better overview of your overall stats you need to add those. However just to view how well you've been performing in the gulag the stats were added to the list. Maybe we can revisit the issue description.

**Comment by saadmujeeb05** [comment]
I see you've added K/D (overall) but not Overall Kills and Overall Deaths 😀

**Pull request merged**
