### PR TITLE
Switch to node-libcurl

### PR DESCRIPTION
**Pull request by jhoogstraat**
This fixes the cloudflare issues which prevent the bot from accessing the tracker.gg api currently.
The system must have curl installed.

### CODE REVIEW

**Review by osama-h-rana — CHANGES_REQUESTED** [review]
The current implementation throws this error: 
image

I believe it can be fixed by this: https://stackoverflow.com/questions/63052127/protractor-node-libcurl-failed-ssl-peer-certificate-or-ssh-remote-key-was-not-o

**Comment by jhoogstraat** [comment]
The CA Certificates should normally be provided by the OS.
I can just include a copy of the Mozilla's CA cert bundle, but thats rather uncommon. Moreover, it creates a new dependency to handle.

What system is the bot running on?

**Comment by osama-h-rana** [comment]
Hmm, I tested the PR on my own windows machine, but I'm not sure if the same problem would exist on Heroku. @Haroon96 maybe you can check?

**Comment by jhoogstraat** [comment]
As it turns out, the error is common: https://github.com/JCMais/node-libcurl/blob/develop/COMMON_ISSUES.md
I can add the third option.

**Comment by jhoogstraat** [comment]
Could you try now @osama-h-rana?

**Review by osama-h-rana — APPROVED** [review]

**Comment by osama-h-rana** [comment]
@jhoogstraat working now on windows, sorry it took so long to review. Kinda busy during the week.

**Review by saadmujeeb05 — APPROVED** [review]

**Review by Haroon96 — APPROVED** [review]

**Pull request merged**
