### PR TITLE
Added support for resurgence stats

### LINKED ISSUE #54: add option for rebirth
hey im on activision and name is mosesjohn
no numbers

### PR DESCRIPTION
**Pull request by osama-h-rana**
Closes #54

### CODE REVIEW

**Review by saadmujeeb05 — APPROVED** [review]

**Review by Haroon96 — APPROVED** [review]

**Review by Haroon96 — COMMENTED** [review]
DIfferentiate between rebirth and resurgence modes. Verdansk Resurgence was a separate game mode from Rebirth Resurgence. Will this command include stats for only Rebirth Island games or resurgence in general?

**Review by Haroon96 — CHANGES_REQUESTED** [review]
Address previous comment.

**Comment by osama-h-rana** [comment]
@Haroon96 as long as the db has the mode id for the resurgence mode, it should pick up those stats as well. I've already added the mode id to the prod db so we should be good to merge this in.

**Comment by osama-h-rana** [comment]
> Address previous comment.

Addressed.

**Review by Haroon96 — APPROVED** [review]

**Pull request merged**
